name: CI - resolve dependencias (testes)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Criar tag
        id: tag
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          git tag build-$TIMESTAMP
          git push origin build-$TIMESTAMP