name: CI - resolve dependencias (testes)

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      tag: rel-${{vars.version}}.${{vars.subversion}}

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: incrementa subversion
        uses: action-pack/increment@v2
        with:
          name: 'subversion'
          token: ${{ secrets.REPO_TOKEN }}

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Criar tag
        id: tag
        env:
          TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git tag $tag
          git push $tag

      - name: Create release package
        env:
          TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          mkdir -p release
          cp -r target/* release/
          cd release
          zip -r ../$tag.zip .
          cd ..

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: $tag.zip
          path: $tag.zip

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/banco:latest
          context: .
          file: .github/workflows/Dockerfile
